### ISSUE TITLE
Response status code does not indicate success: 403 (Forbidden) 

### ISSUE THREAD

**Issue by Nellaimuthuvel** [shaked6540/YoutubePlaylistDownloader#356] opened 2024-09-25 06:41 UTC

**Comment by nazmul-nhb** [comment] 2024-09-25 18:26
having the same issue

**Comment by cristianst85** [comment] 2024-09-28 12:11
Duplicate of #354.

**Comment by shaked6540** [comment] 2024-10-04 20:05
Should be solved in the latest update (1.9.25)

**Closed by shaked6540** 2024-10-04 20:05 UTC
