### ISSUE TITLE
Getting a 403 Error whenever i try to download songs....

### ISSUE THREAD

**Issue by Eliteben** [shaked6540/YoutubePlaylistDownloader#359] opened 2024-09-26 01:32 UTC
I've tried over 20 different videos and none of them seem to work. Here is the error I'm getting:

Here is a list of the videos that could not be downloaded, and the reason why: 
Ed Sheeran - Shape of You (Official Music Video) Reason: Response status code does not indicate success: 403 (Forbidden).

**Comment by Alireza-F-kenedy** [comment] 2024-09-26 10:22
Yep, same thing happened to me. I tried installing the program twice on two different computers, but it didn't fix it

**Comment by fat-sycophant** [comment] 2024-09-27 05:09
me too

**Comment by TheOneTruth1611** [comment] 2024-09-27 11:39
Same here

**Comment by cristianst85** [comment] 2024-09-28 12:12
Duplicate of #354.

**Comment by shaked6540** [comment] 2024-10-04 20:06
Should be solved in the latest update (1.9.25)

**Closed by shaked6540** 2024-10-04 20:06 UTC
