### ISSUE TITLE
Sign in to confrim you're not a bot ERROR

### ISSUE THREAD

**Issue by AlexBanu46** [shaked6540/YoutubePlaylistDownloader#361] opened 2024-09-26 15:56 UTC
Here is a list of the videos that could not be downloaded, and the reason why: 
Sa Petrecem Romaneste Reason: Video 'wNIE0XurcWI' is unplayable. Reason: 'Sign in to confirm you’re not a bot'.
Adriana Antoni - A zis tata catre mine ( Official Video ) Reason: Video '470jvySV1Sw' is unplayable. Reason: 'Sign in to confirm you’re not a bot'.
Bianca Barbu - COLAJ ASCULTARE 2023 - Muzica de petrecere LIVE (COVER) Reason: Video 'ETV_IxJlGpI' is unplayable. Reason: 'Sign in to confirm you’re not a bot'.
Sarba De La Jiu Reason: Video 'J78pG1fFo7M' is unplayable. Reason: 'Sign in to confirm you’re not a bot'.
Mandra Mea Draguta Reason: Video 'GkIOgm68aP4' is unplayable. Reason: 'Sign in to confirm you’re not a bot'.

And this happens to every video or audio i am trying to download...

**Comment by Darknecr0mancer** [comment] 2024-09-27 18:34
Out of my 512 song playlist only 10 of them didn't get this error.

**Comment by cristianst85** [comment] 2024-09-28 12:13
Duplicate of #354.

**Comment by shaked6540** [comment] 2024-10-04 20:07
Youtube thinks you're a bot, nothing you can do about it really, wait a couple of hours/days and try again. I'm not adding sign in option to the program because of various security reasons and as far as I saw from other downloaders, signing in does not solve it

**Closed by shaked6540** 2024-10-04 20:07 UTC

**Comment by James-Fire** [comment] 2024-11-20 04:53
Can you not rate-limit it on your end?

Make a configureable setting to limit videos/time, or limit download speed?
