### ISSUE TITLE
403 error for everything - help! 

### ISSUE THREAD

**Issue by ajachwak** [shaked6540/YoutubePlaylistDownloader#358] opened 2024-09-25 22:12 UTC
I see this issue has been submitted multiple times. Please help when you have the chance!

**Comment by cristianst85** [comment] 2024-09-28 12:12
So you opened another one. Duplicate of #354.

**Comment by shaked6540** [comment] 2024-10-04 20:06
Should be solved in the latest update (1.9.25)

**Closed by shaked6540** 2024-10-04 20:06 UTC
