### ISSUE TITLE
Playlist link will not work

### ISSUE THREAD

**Issue by PJBoogie** [shaked6540/YoutubePlaylistDownloader#364] opened 2024-09-29 05:09 UTC
I paste the link into the space for bulk download, but nothing will come up in the queue. I don't understand, here's the link. Can you tell me what's wrong with it? Thank you!

https://www.youtube.com/playlist?list=PLw8AM0LVcN7g4goEaqoz06KI89fDq6_VT

**Comment by cristianst85** [comment] 2024-09-30 15:06
Possible a duplicate of https://github.com/shaked6540/YoutubePlaylistDownloader/issues/354.

**Comment by shaked6540** [comment] 2024-10-04 20:07
Should be solved in the latest update (1.9.25)

**Closed by shaked6540** 2024-10-04 20:07 UTC

**Comment by PJBoogie** [comment] 2024-10-04 20:12
Ok, thank you.
