### ISSUE TITLE
nothing is dowloading 

### ISSUE THREAD

**Issue by rjitani** [shaked6540/YoutubePlaylistDownloader#362] opened 2024-09-28 01:33 UTC
Here is a list of the videos that could not be downloaded, and the reason why: 
Tauba Tauba | Bad Newz | Vicky Kaushal | Triptii Dimri | Karan Aujla Reason: Response status code does not indicate success: 403 (Forbidden).
Shubh - Cheques (Official Music Video) Reason: Response status code does not indicate success: 403 (Forbidden).
Mere Bhole Nath (Video) Jubin Nautiyal | Payal Dev, Vishal Bagh | Devotional Song | Bhushan Kumar Reason: Response status code does not indicate success: 403 (Forbidden).
YODHA: Zindagi Tere Naam (Song) | Sidharth Malhotra, Raashii Khanna | Vishal Mishra Reason: Response status code does not indicate success: 403 (Forbidden).
Dekhha Tenu | Mr. & Mrs. Mahi | Rajkummar Rao, Janhvi Kapoor | Mohd. Faiz | Jaani | Aadesh S| Sameer Reason: Response status code does not indicate success: 403 (Forbidden).
ANIMAL: SATRANGA(Song) Ranbir Kapoor,Rashmika|Sandeep V|Arijit,Shreyas P,Siddharth-Garima |Bhushan K Reason: Response status code does not indicate success: 403 (Forbidden).
Jitni Dafa - Lyrical | PARMANU | John Abraham , Diana | Jeet Gannguli | RashmiVirag Reason: Video 'AvgFmr-ckpk' is unplayable. Reason: 'Sign in to confirm you’re not a bot'.
Chann Chann (Official Video)| Jordan Sandhu Ft Zareen Khan | Desi Crew | Latest Punjabi Song 2021 Reason: Response status code does not indicate success: 403 (Forbidden).
Powerful HANUMAN CHALISA from HanuMan | Prasanth Varma | Primeshow Entertainment Reason: Response status code does not indicate success: 403 (Forbidden).
KAUN TUJHE  Lyrical | M.S. DHONI -THE UNTOLD STORY | Amaal Mallik Palak | Sushant Singh Disha Patani Reason: Response status code does not indicate success: 403 (Forbidden).
Teri Yaadon Mein Lyrical Video | The Killer | K K, Shreya Ghosal | Emraan Hashmi, Nisha Kothari Reason: Response status code does not indicate success: 403 (Forbidden).
#Video | चश्मा लगाके हैंडसम लगातार | #Khushi Kakkar | Ft. #Parul Yadav | New #Bhojpuri Song 2024 Reason: Response status code does not indicate success: 403 (Forbidden).
Is Qadar | Tulsi Kumar, Darshan Raval | Sachet-Parampara | Sayeed Quadri | Arvindr K | Bhushan K Reason: Response status code does not indicate success: 403 (Forbidden).
Saware Mashup | SICKVED | 2024 Reason: Response status code does not indicate success: 403 (Forbidden).
Jogi - Lyrical |Shaadi Mein Zaroor Aana |Rajkummar Rao,Kriti K|Arko ft Aakanksha Sharma Reason: Response status code does not indicate success: 403 (Forbidden).

**Comment by cristianst85** [comment] 2024-09-28 12:12
Duplicate of #354.

**Comment by shaked6540** [comment] 2024-10-04 20:07
Should be solved in the latest update (1.9.25)

**Closed by shaked6540** 2024-10-04 20:07 UTC
